#!/usr/bin/env python3
import csv
from pathlib import Path

# Paste your JS-style array BELOW, exactly as-is (keys unquoted like id:, topicCn:, answerFr:, etc.)
RAW_JS = r"""
[
          { type: "section", titleCn: "T1", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `De réserver un livre.`, answerCn: `预订一本书。` },
          { id: 2, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 3, topicCn: "", answerFr: `La promotion d'un moyen d'échanges entre les différentes nationalités.`, answerCn: `促进不同国籍之间交流的方式。` },
          { id: 4, topicCn: "", answerFr: `Elles se rebellent très vite face à l'autorité familiale au quotidien.`, answerCn: `她们在日常生活中很快反抗家庭权威。` },
          { id: 5, topicCn: "", answerFr: `Découvrir une région de France.`, answerCn: `探索法国的一个地区。` },
          { id: 6, topicCn: "", answerFr: `Pour se réchauffer.`, answerCn: `为了取暖。` },
          { id: 7, topicCn: "", answerFr: `Elle a arrêté d'exercer sa profession.`, answerCn: `她停止从事自己的职业。` },
          { id: 8, topicCn: "", answerFr: `La musique.`, answerCn: `音乐。` },
          { id: 9, topicCn: "", answerFr: `Elle a travaillé avec une institutrice américaine.`, answerCn: `她曾与一位美国女教师合作。` },
          { id: 10, topicCn: "", answerFr: `D’un appel à projets imaginaires.`, answerCn: `来自一次虚构项目征集。` },

          { type: "section", titleCn: "T2", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `La circulation routière est coupée.`, answerCn: `道路交通被中断。` },
          { id: 2, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 3, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 4, topicCn: "", answerFr: `Ils déplorent un manque d'information.`, answerCn: `他们对信息不足表示遗憾。` },
          { id: 5, topicCn: "", answerFr: `Le stationnement est devenu payant.`, answerCn: `停车现在变成收费的。` },
          { id: 6, topicCn: "", answerFr: `La variété de la programmation.`, answerCn: `节目安排的多样性。` },
          { id: 7, topicCn: "", answerFr: `La recherche d'un appartement est rapide.`, answerCn: `寻找公寓的过程很快。` },
          { id: 8, topicCn: "", answerFr: `Parce qu'elles avaient lieu tôt dans l'année scolaire.`, answerCn: `因为它们发生在学年初期。` },
          { id: 9, topicCn: "", answerFr: `L'état actuel de la biodiversité.`, answerCn: `当前的生物多样性状况。` },
          { id: 10, topicCn: "", answerFr: `D'expérimenter une manière différente de voyager.`, answerCn: `尝试一种不同的旅行方式。` },

          { type: "section", titleCn: "T3", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Un de ses enfants a du mal à respecter les règles du jeu.`, answerCn: `他的一个孩子难以遵守游戏规则。` },
          { id: 2, topicCn: "", answerFr: `De se montrer prudent.`, answerCn: `表现得谨慎。` },
          { id: 3, topicCn: "", answerFr: `La mutation de l'habitat des abeilles.`, answerCn: `蜜蜂栖息地的变化。` },
          { id: 4, topicCn: "", answerFr: `La mobilité.`, answerCn: `流动性。` },
          { id: 5, topicCn: "", answerFr: `Il offre des services de qualité supérieure.`, answerCn: `他提供高质量服务。` },
          { id: 6, topicCn: "", answerFr: `Elle a d'abord une vocation caritative.`, answerCn: `她最初有慈善使命。` },
          { id: 7, topicCn: "", answerFr: `Il faut prouver la nécessité de la démarche.`, answerCn: `必须证明这一行动的必要性。` },
          { id: 8, topicCn: "", answerFr: `Il pense qu'il aurait dû être prévenu.`, answerCn: `他认为本应有人通知他。` },
          { id: 9, topicCn: "", answerFr: `Les critères de sélection sont particulièrement stricts.`, answerCn: `选拔标准非常严格。` },
          { id: 10, topicCn: "", answerFr: `De maigrir plus rapidement.`, answerCn: `更快地减肥。` },

          { type: "section", titleCn: "T4", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il s'adresse aux acheteurs à Noël.`, answerCn: `他面向圣诞节购物者。` },
          { id: 2, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 3, topicCn: "", answerFr: `L'absence de vérification des sources.`, answerCn: `缺乏对信息来源的核实。` },
          { id: 4, topicCn: "", answerFr: `Parce qu'elle souffre et qu'elle est fatiguée.`, answerCn: `因为她感到痛苦和疲惫。` },
          { id: 5, topicCn: "", answerFr: `D'une sélection de films.`, answerCn: `一系列电影的选择。` },
          { id: 6, topicCn: "", answerFr: `Il veut éviter toute publicité personnelle.`, answerCn: `他想避免任何个人宣传。` },
          { id: 7, topicCn: "", answerFr: `Il avait du mal à accepter ses choix.`, answerCn: `他难以接受自己的选择。` },
          { id: 8, topicCn: "", answerFr: `La création d'un livre pour enfant de qualité est un travail d'équipe.`, answerCn: `制作高质量儿童书是团队合作。` },
          { id: 9, topicCn: "", answerFr: `Des comportements alimentaires.`, answerCn: `饮食行为。` },
          { id: 10, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T5", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Le recrutement se fonde sur l'expérience.`, answerCn: `招聘以经验为基础。` },
          { id: 2, topicCn: "", answerFr: `Les travaux nécessaires ne sont pas encore achevés.`, answerCn: `必要工程尚未完成。` },
          { id: 3, topicCn: "", answerFr: `Des activités en faveur du développement durable.`, answerCn: `支持可持续发展的活动。` },
          { id: 4, topicCn: "", answerFr: `Comment recycler son sapin ?`, answerCn: `如何回收圣诞树？` },
          { id: 5, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随伴侣。` },
          { id: 6, topicCn: "", answerFr: `Ils osent davantage partir à l'étranger qu'auparavant.`, answerCn: `他们比以前更敢出国。` },
          { id: 7, topicCn: "", answerFr: `Un récit autobiographique ancré dans la vie intellectuelle du siècle dernier.`, answerCn: `一部扎根于上世纪知识生活的自传。` },
          { id: 8, topicCn: "", answerFr: `De son emploi du temps professionnel.`, answerCn: `关于他的职业时间安排。` },
          { id: 9, topicCn: "", answerFr: `Elle est restée toute seule.`, answerCn: `她一直独自一人。` },
          { id: 10, topicCn: "", answerFr: `Sa fréquentation des salles dès son plus jeune âge.`, answerCn: `她从很小就经常去这些场所。` },

          { type: "section", titleCn: "T6", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得脆弱。` },
          { id: 2, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 3, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 4, topicCn: "", answerFr: `Des formules adaptées à chaque client.`, answerCn: `为每位客户量身定制的方案。` },
          { id: 5, topicCn: "", answerFr: `L'ouverture de formations artistiques.`, answerCn: `开设艺术培训课程。` },
          { id: 6, topicCn: "", answerFr: `Privilégier une agriculture sans produit chimique.`, answerCn: `优先发展无化学品农业。` },
          { id: 7, topicCn: "", answerFr: `Le confort que leur procure leur structure familiale.`, answerCn: `家庭结构带给他们的安全感。` },
          { id: 8, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持积极态度。` },
          { id: 9, topicCn: "", answerFr: `Son parcours d’apprentissage.`, answerCn: `他的学习经历。` },
          { id: 10, topicCn: "", answerFr: `D’élargir sa recherche d'emploi à d'autres domaines.`, answerCn: `把求职范围扩大到其他领域。` },

          { type: "section", titleCn: "T7", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `La nécessité de trouver un travail.`, answerCn: `需要找到一份工作。` },
          { id: 2, topicCn: "", answerFr: `Elle conseille une activité physique.`, answerCn: `她建议进行体育活动。` },
          { id: 3, topicCn: "", answerFr: `Des activités en faveur du développement durable.`, answerCn: `促进可持续发展的活动。` },
          { id: 4, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 5, topicCn: "", answerFr: `Des formules adaptées à chaque client.`, answerCn: `适合每个客户的方案。` },
          { id: 6, topicCn: "", answerFr: `Parce qu'elle souhaite changer de destination estivale.`, answerCn: `因为她想换一个夏季度假地。` },
          { id: 7, topicCn: "", answerFr: `En collaborant à des activités de bénévolat.`, answerCn: `通过参与志愿活动。` },
          { id: 8, topicCn: "", answerFr: `Ils sont cultivés par des gens sans emploi.`, answerCn: `它们由失业者种植。` },
          { id: 9, topicCn: "", answerFr: `Son parcours d’apprentissage.`, answerCn: `他的学习历程。` },
          { id: 10, topicCn: "", answerFr: `Ils devront demander le remboursement de leur billet par écrit.`, answerCn: `他们必须书面申请退票。` },

          { type: "section", titleCn: "T8", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天好。` },
          { id: 2, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 3, topicCn: "", answerFr: `Pour être autonome face aux petits travaux de la maison.`, answerCn: `为了能自己处理家庭小维修。` },
          { id: 4, topicCn: "", answerFr: `Un point de vue sur la situation mondiale aujourd’hui.`, answerCn: `对当今世界局势的观点。` },
          { id: 5, topicCn: "", answerFr: `De partager sa salle de bain.`, answerCn: `共用浴室。` },
          { id: 6, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样的课程教育。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有做自己老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Des comportements alimentaires.`, answerCn: `饮食行为。` },
          { id: 9, topicCn: "", answerFr: `D’élargir sa recherche d'emploi à d'autres domaines.`, answerCn: `扩大求职领域。` },
          { id: 10, topicCn: "", answerFr: `L’utilisation d’un matériau unique.`, answerCn: `使用单一材料。` },

          { type: "section", titleCn: "T9", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il est possible qu'il soit renvoyé.`, answerCn: `他有可能被解雇。` },
          { id: 2, topicCn: "", answerFr: `Elle travaille dans un restaurant.`, answerCn: `她在一家餐馆工作。` },
          { id: 3, topicCn: "", answerFr: `Elle est terrorisée par les animaux aquatiques.`, answerCn: `她害怕水生动物。` },
          { id: 4, topicCn: "", answerFr: `Pour plonger dans l’imaginaire.`, answerCn: `为了沉浸在想象世界。` },
          { id: 5, topicCn: "", answerFr: `Elle a été impressionnée par le son des cordes qu'on peut faire vibrer longtemps.`, answerCn: `她被能长时间震动的弦乐声音打动。` },
          { id: 6, topicCn: "", answerFr: `Parce que la consommation dépend avant tout du pouvoir d'achat.`, answerCn: `因为消费首先取决于购买力。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Il diminue les efforts de ceux qui le suivent.`, answerCn: `它减少后来者的努力。` },
          { id: 9, topicCn: "", answerFr: `Elles ont la notion du temps chronologique.`, answerCn: `她们具有时间顺序概念。` },
          { id: 10, topicCn: "", answerFr: `Expliquer pourquoi on attend de la musique au lieu des programmes habituels.`, answerCn: `解释为什么播放音乐而不是正常节目。` },

          { type: "section", titleCn: "T10", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Visiter une ville.`, answerCn: `参观一座城市。` },
          { id: 2, topicCn: "", answerFr: `Le secrétariat de son département.`, answerCn: `他所在部门的秘书处。` },
          { id: 3, topicCn: "", answerFr: `Ils jouent aux cartes.`, answerCn: `他们在打牌。` },
          { id: 4, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `体育活动相关限制。` },
          { id: 5, topicCn: "", answerFr: `Elles se rebellent très vite face à l’autorité familiale au quotidien.`, answerCn: `她们日常生活中很快反抗家庭权威。` },
          { id: 6, topicCn: "", answerFr: `Il a travaillé dans un commerce.`, answerCn: `他曾在一家商店工作。` },
          { id: 7, topicCn: "", answerFr: `Il s’est d'abord fait connaître auprès des étudiants.`, answerCn: `他最初在学生中出名。` },
          { id: 8, topicCn: "", answerFr: `En les incitant à travailler de manière collaborative.`, answerCn: `通过鼓励他们合作学习。` },
          { id: 9, topicCn: "", answerFr: `Établir un certificat médical.`, answerCn: `开具医疗证明。` },
          { id: 10, topicCn: "", answerFr: `L’implication active de tous les habitants.`, answerCn: `所有居民的积极参与。` },

          { type: "section", titleCn: "T11", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Les conditions de recrutement sont plus difficiles aujourd’hui.`, answerCn: `如今招聘条件更加困难。` },
          { id: 2, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 3, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为一种休闲活动。` },
          { id: 4, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业发展的机会。` },
          { id: 5, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随她的伴侣。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论自己品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d’être son propre patron.`, answerCn: `拥有做自己老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Des révisions d’un examen.`, answerCn: `准备一场考试复习。` },
          { id: 9, topicCn: "", answerFr: `Faciliter la consommation de produits sains.`, answerCn: `促进健康食品消费。` },
          { id: 10, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T12", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Une sortie au théâtre.`, answerCn: `去剧院看戏。` },
          { id: 2, topicCn: "", answerFr: `D’un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 3, topicCn: "", answerFr: `La météo était très mauvaise.`, answerCn: `天气非常糟糕。` },
          { id: 4, topicCn: "", answerFr: `Leur salaire est insuffisant.`, answerCn: `他们的工资不足。` },
          { id: 5, topicCn: "", answerFr: `Les premiers mois d’un bébé.`, answerCn: `婴儿最初几个月。` },
          { id: 6, topicCn: "", answerFr: `Les gens cherchent davantage à être heureux.`, answerCn: `人们更加追求幸福。` },
          { id: 7, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 8, topicCn: "", answerFr: `Il pratique son art depuis l’enfance.`, answerCn: `他从小就从事自己的艺术。` },
          { id: 9, topicCn: "", answerFr: `De sensibiliser l’opinion.`, answerCn: `提高公众意识。` },
          { id: 10, topicCn: "", answerFr: `Adopter un mode de vie collectif responsable.`, answerCn: `采取负责任的集体生活方式。` },

          { type: "section", titleCn: "T13", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得不稳定。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `与体育活动相关的限制。` },
          { id: 4, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 5, topicCn: "", answerFr: `Le souci du bien-être des personnes hospitalisées.`, answerCn: `关注住院者的福祉。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论所品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `S’exprimer avec précision.`, answerCn: `表达准确。` },
          { id: 8, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持乐观态度。` },
          { id: 9, topicCn: "", answerFr: `Les habitudes alimentaires des élèves sont difficiles à modifier.`, answerCn: `学生的饮食习惯难以改变。` },
          { id: 10, topicCn: "", answerFr: `L’absence de formation à l’élaboration du budget.`, answerCn: `缺乏预算制定培训。` },

          { type: "section", titleCn: "T14", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il fait plus beau qu’hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Ils annonçaient de fausses promotions.`, answerCn: `他们宣布虚假的促销。` },
          { id: 4, topicCn: "", answerFr: `Il n’y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 5, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 6, topicCn: "", answerFr: `Amener l’élève à participer à sa propre formation.`, answerCn: `让学生参与自己的学习。` },
          { id: 7, topicCn: "", answerFr: `Ils partent à la montagne.`, answerCn: `他们去山里。` },
          { id: 8, topicCn: "", answerFr: `De son emploi du temps professionnel.`, answerCn: `关于他的职业时间安排。` },
          { id: 9, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门中的任务分配。` },
          { id: 10, topicCn: "", answerFr: `D’expérimenter une manière différente de voyager.`, answerCn: `尝试不同的旅行方式。` },

          { type: "section", titleCn: "T15", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 2, topicCn: "", answerFr: `Son œuvre est présentée en France.`, answerCn: `他的作品在法国展出。` },
          { id: 3, topicCn: "", answerFr: `Parce qu’ils ont été adoptés dans des pays différents.`, answerCn: `因为他们在不同国家被收养。` },
          { id: 4, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为休闲活动。` },
          { id: 5, topicCn: "", answerFr: `Elle a vite appris son métier.`, answerCn: `她很快学会了自己的职业。` },
          { id: 6, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés.`, answerCn: `环境课程数量增加。` },
          { id: 7, topicCn: "", answerFr: `Elle permet à des jeunes d’habiter chez des personnes âgées.`, answerCn: `它让年轻人与老人同住。` },
          { id: 8, topicCn: "", answerFr: `Il est protégé par des apports lexicaux variés.`, answerCn: `它受到多样词汇的保护。` },
          { id: 9, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门任务分配。` },
          { id: 10, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种无论学习什么学科都能帮助学习的工具。` },

          { type: "section", titleCn: "T16", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `La circulation routière est coupée.`, answerCn: `道路交通被中断。` },
          { id: 2, topicCn: "", answerFr: `Il est possible qu'il soit renvoyé.`, answerCn: `他有可能被解雇。` },
          { id: 3, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 4, topicCn: "", answerFr: `Il n’y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 5, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样的课程教育。` },
          { id: 6, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés.`, answerCn: `环境相关课程数量增加。` },
          { id: 7, topicCn: "", answerFr: `Elle permet à des jeunes d’habiter chez des personnes âgées.`, answerCn: `它让年轻人与老人同住。` },
          { id: 8, topicCn: "", answerFr: `Les avis qu'ils partagent au sujet de l'école.`, answerCn: `他们关于学校问题分享的看法。` },
          { id: 9, topicCn: "", answerFr: `Assister de façon discrète le client.`, answerCn: `低调地协助客户。` },
          { id: 10, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种无论学习什么学科都能帮助学习的工具。` },

          { type: "section", titleCn: "T17", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Le recrutement se fonde sur l'expérience.`, answerCn: `招聘基于经验。` },
          { id: 2, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 3, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为一种休闲活动。` },
          { id: 4, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业机会。` },
          { id: 5, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随伴侣。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论自己品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Des révisions d’un examen.`, answerCn: `准备考试复习。` },
          { id: 9, topicCn: "", answerFr: `Faciliter la consommation de produits sains.`, answerCn: `促进健康食品消费。` },
          { id: 10, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T18", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Une sortie au théâtre.`, answerCn: `去剧院看戏。` },
          { id: 2, topicCn: "", answerFr: `D’un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 3, topicCn: "", answerFr: `La météo était très mauvaise.`, answerCn: `天气非常糟糕。` },
          { id: 4, topicCn: "", answerFr: `Leur salaire est insuffisant.`, answerCn: `他们的工资不足。` },
          { id: 5, topicCn: "", answerFr: `Les premiers mois d’un bébé.`, answerCn: `婴儿最初几个月。` },
          { id: 6, topicCn: "", answerFr: `Les gens cherchent davantage à être heureux.`, answerCn: `人们更加追求幸福。` },
          { id: 7, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 8, topicCn: "", answerFr: `Il pratique son art depuis l’enfance.`, answerCn: `他从小就从事自己的艺术。` },
          { id: 9, topicCn: "", answerFr: `De sensibiliser l’opinion.`, answerCn: `提高公众意识。` },
          { id: 10, topicCn: "", answerFr: `Adopter un mode de vie collectif responsable.`, answerCn: `采取负责任的集体生活方式。` },

          { type: "section", titleCn: "T19", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得不稳定。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `与体育活动相关的限制。` },
          { id: 4, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 5, topicCn: "", answerFr: `Le souci du bien-être des personnes hospitalisées.`, answerCn: `关注住院者的福祉。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论所品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `S’exprimer avec précision.`, answerCn: `表达准确。` },
          { id: 8, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持乐观态度。` },
          { id: 9, topicCn: "", answerFr: `Les habitudes alimentaires des élèves sont difficiles à modifier.`, answerCn: `学生的饮食习惯难以改变。` },
          { id: 10, topicCn: "", answerFr: `L’absence de formation à l’élaboration du budget.`, answerCn: `缺乏预算制定培训。` },

          { type: "section", titleCn: "T20", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il fait plus beau qu’hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Ils annonçaient de fausses promotions.`, answerCn: `他们宣布虚假的促销。` },
          { id: 4, topicCn: "", answerFr: `Il n’y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 5, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 6, topicCn: "", answerFr: `Amener l’élève à participer à sa propre formation.`, answerCn: `让学生参与自己的学习。` },
          { id: 7, topicCn: "", answerFr: `Ils partent à la montagne.`, answerCn: `他们去山里。` },
          { id: 8, topicCn: "", answerFr: `De son emploi du temps professionnel.`, answerCn: `关于他的职业时间安排。` },
          { id: 9, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门中的任务分配。` },
          { id: 10, topicCn: "", answerFr: `D’expérimenter une manière différente de voyager.`, answerCn: `尝试不同的旅行方式。` },

          { type: "section", titleCn: "T21", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 2, topicCn: "", answerFr: `Son œuvre est présentée en France.`, answerCn: `他的作品在法国展出。` },
          { id: 3, topicCn: "", answerFr: `Parce qu’ils ont été adoptés dans des pays différents.`, answerCn: `因为他们在不同国家被收养。` },
          { id: 4, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为休闲活动。` },
          { id: 5, topicCn: "", answerFr: `Elle a vite appris son métier.`, answerCn: `她很快学会了自己的职业。` },
          { id: 6, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés.`, answerCn: `环境课程数量增加。` },
          { id: 7, topicCn: "", answerFr: `Elle permet à des jeunes d’habiter chez des personnes âgées.`, answerCn: `它让年轻人与老人同住。` },
          { id: 8, topicCn: "", answerFr: `Il est protégé par des apports lexicaux variés.`, answerCn: `它受到多样词汇的保护。` },
          { id: 9, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门任务分配。` },
          { id: 10, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种无论学习什么学科都能帮助学习的工具。` },

          { type: "section", titleCn: "T22", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `La circulation routière est coupée.`, answerCn: `道路交通被中断。` },
          { id: 2, topicCn: "", answerFr: `Il est possible qu'il soit renvoyé.`, answerCn: `他有可能被解雇。` },
          { id: 3, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 4, topicCn: "", answerFr: `Il n’y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 5, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 6, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés.`, answerCn: `环境课程数量增加。` },
          { id: 7, topicCn: "", answerFr: `Elle permet à des jeunes d’habiter chez des personnes âgées.`, answerCn: `它让年轻人与老人同住。` },
          { id: 8, topicCn: "", answerFr: `Les avis qu'ils partagent au sujet de l'école.`, answerCn: `他们关于学校问题分享的看法。` },
          { id: 9, topicCn: "", answerFr: `Assister de façon discrète le client.`, answerCn: `低调地协助客户。` },
          { id: 10, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种无论学习什么学科都能帮助学习的工具。` },

          { type: "section", titleCn: "T23", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Le recrutement se fonde sur l'expérience.`, answerCn: `招聘基于经验。` },
          { id: 2, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 3, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为休闲活动。` },
          { id: 4, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业机会。` },
          { id: 5, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随伴侣。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论自己品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Des révisions d’un examen.`, answerCn: `准备考试复习。` },
          { id: 9, topicCn: "", answerFr: `Faciliter la consommation de produits sains.`, answerCn: `促进健康食品消费。` },
          { id: 10, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T24", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Une sortie au théâtre.`, answerCn: `去剧院看戏。` },
          { id: 2, topicCn: "", answerFr: `D’un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 3, topicCn: "", answerFr: `La météo était très mauvaise.`, answerCn: `天气非常糟糕。` },
          { id: 4, topicCn: "", answerFr: `Leur salaire est insuffisant.`, answerCn: `他们的工资不足。` },
          { id: 5, topicCn: "", answerFr: `Les premiers mois d’un bébé.`, answerCn: `婴儿最初几个月。` },
          { id: 6, topicCn: "", answerFr: `Les gens cherchent davantage à être heureux.`, answerCn: `人们更加追求幸福。` },
          { id: 7, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 8, topicCn: "", answerFr: `Il pratique son art depuis l’enfance.`, answerCn: `他从小从事艺术。` },
          { id: 9, topicCn: "", answerFr: `De sensibiliser l’opinion.`, answerCn: `提高公众意识。` },
          { id: 10, topicCn: "", answerFr: `Adopter un mode de vie collectif responsable.`, answerCn: `采取负责任的集体生活方式。` },

          { type: "section", titleCn: "T25", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得不稳定。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `与体育活动相关的限制。` },
          { id: 4, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 5, topicCn: "", answerFr: `Le souci du bien-être des personnes hospitalisées.`, answerCn: `关注住院者福祉。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `S’exprimer avec précision.`, answerCn: `表达准确。` },
          { id: 8, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持乐观态度。` },
          { id: 9, topicCn: "", answerFr: `Les habitudes alimentaires des élèves sont difficiles à modifier.`, answerCn: `学生饮食习惯难改变。` },
          { id: 10, topicCn: "", answerFr: `L’absence de formation à l’élaboration du budget.`, answerCn: `缺乏预算制定培训。` },


          { type: "section", titleCn: "T26", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Elle a réalisé un projet artistique.`, answerCn: `她完成了一个艺术项目。` },
          { id: 2, topicCn: "", answerFr: `Être ouvert aux autres.`, answerCn: `对他人保持开放。` },
          { id: 3, topicCn: "", answerFr: `Parce qu'il en reste encore chez elles.`, answerCn: `因为她们那里还有剩余。` },
          { id: 4, topicCn: "", answerFr: `Il a travaillé dans un commerce.`, answerCn: `他曾在一家商店工作。` },
          { id: 5, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业发展的机会。` },
          { id: 6, topicCn: "", answerFr: `Ils osent davantage partir à l'étranger qu'auparavant.`, answerCn: `他们比以前更敢出国。` },
          { id: 7, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 8, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持积极态度。` },
          { id: 9, topicCn: "", answerFr: `Son parcours d’apprentissage.`, answerCn: `他的学习经历。` },
          { id: 10, topicCn: "", answerFr: `D’élargir sa recherche d'emploi à d'autres domaines.`, answerCn: `扩大求职领域。` },

          { type: "section", titleCn: "T27", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `La nécessité de trouver un travail.`, answerCn: `需要找到一份工作。` },
          { id: 2, topicCn: "", answerFr: `Elle conseille une activité physique.`, answerCn: `她建议进行体育活动。` },
          { id: 3, topicCn: "", answerFr: `Des activités en faveur du développement durable.`, answerCn: `促进可持续发展的活动。` },
          { id: 4, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 5, topicCn: "", answerFr: `Des formules adaptées à chaque client.`, answerCn: `为客户量身定制方案。` },
          { id: 6, topicCn: "", answerFr: `Parce qu'elle souhaite changer de destination estivale.`, answerCn: `因为她想换一个夏季度假地。` },
          { id: 7, topicCn: "", answerFr: `En collaborant à des activités de bénévolat.`, answerCn: `通过参与志愿活动。` },
          { id: 8, topicCn: "", answerFr: `Ils sont cultivés par des gens sans emploi.`, answerCn: `它们由失业者种植。` },
          { id: 9, topicCn: "", answerFr: `Son parcours d’apprentissage.`, answerCn: `他的学习历程。` },
          { id: 10, topicCn: "", answerFr: `Ils devront demander le remboursement de leur billet par écrit.`, answerCn: `他们必须书面申请退票。` },

          { type: "section", titleCn: "T28", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 2, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 3, topicCn: "", answerFr: `Pour être autonome face aux petits travaux de la maison.`, answerCn: `为了自己处理家庭小维修。` },
          { id: 4, topicCn: "", answerFr: `Un point de vue sur la situation mondiale aujourd’hui.`, answerCn: `对当今世界局势的观点。` },
          { id: 5, topicCn: "", answerFr: `De partager sa salle de bain.`, answerCn: `共用浴室。` },
          { id: 6, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有做自己老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Des comportements alimentaires.`, answerCn: `饮食行为。` },
          { id: 9, topicCn: "", answerFr: `D’élargir sa recherche d'emploi à d'autres domaines.`, answerCn: `扩大求职领域。` },
          { id: 10, topicCn: "", answerFr: `L’utilisation d’un matériau unique.`, answerCn: `使用单一材料。` },

          { type: "section", titleCn: "T29", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il est possible qu'il soit renvoyé.`, answerCn: `他可能会被解雇。` },
          { id: 2, topicCn: "", answerFr: `Elle travaille dans un restaurant.`, answerCn: `她在餐馆工作。` },
          { id: 3, topicCn: "", answerFr: `Elle est terrorisée par les animaux aquatiques.`, answerCn: `她害怕水生动物。` },
          { id: 4, topicCn: "", answerFr: `Pour plonger dans l’imaginaire.`, answerCn: `为了沉浸在想象世界。` },
          { id: 5, topicCn: "", answerFr: `Elle a été impressionnée par le son des cordes qu'on peut faire vibrer longtemps.`, answerCn: `她被弦乐声音打动。` },
          { id: 6, topicCn: "", answerFr: `Parce que la consommation dépend avant tout du pouvoir d'achat.`, answerCn: `因为消费取决于购买力。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Il diminue les efforts de ceux qui le suivent.`, answerCn: `它减少后来者的努力。` },
          { id: 9, topicCn: "", answerFr: `Elles ont la notion du temps chronologique.`, answerCn: `她们具有时间顺序概念。` },
          { id: 10, topicCn: "", answerFr: `Expliquer pourquoi on attend de la musique au lieu des programmes habituels.`, answerCn: `解释为何播放音乐而不是正常节目。` },

          { type: "section", titleCn: "T30", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Visiter une ville.`, answerCn: `参观一座城市。` },
          { id: 2, topicCn: "", answerFr: `Le secrétariat de son département.`, answerCn: `他部门的秘书处。` },
          { id: 3, topicCn: "", answerFr: `Ils jouent aux cartes.`, answerCn: `他们在打牌。` },
          { id: 4, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `体育活动相关限制。` },
          { id: 5, topicCn: "", answerFr: `Elles se rebellent très vite face à l’autorité familiale au quotidien.`, answerCn: `她们日常反抗家庭权威。` },
          { id: 6, topicCn: "", answerFr: `Il a travaillé dans un commerce.`, answerCn: `他曾在一家商店工作。` },
          { id: 7, topicCn: "", answerFr: `Il s’est d'abord fait connaître auprès des étudiants.`, answerCn: `他最初在学生中出名。` },
          { id: 8, topicCn: "", answerFr: `En les incitant à travailler de manière collaborative.`, answerCn: `鼓励他们合作学习。` },
          { id: 9, topicCn: "", answerFr: `Établir un certificat médical.`, answerCn: `开具医疗证明。` },
          { id: 10, topicCn: "", answerFr: `L’implication active de tous les habitants.`, answerCn: `所有居民的积极参与。` },

          { type: "section", titleCn: "T31", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Le recrutement se fonde sur l'expérience.`, answerCn: `招聘以经验为基础。` },
          { id: 2, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 3, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为休闲活动。` },
          { id: 4, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业发展机会。` },
          { id: 5, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随伴侣。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论自己品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Des révisions d’un examen.`, answerCn: `准备考试复习。` },
          { id: 9, topicCn: "", answerFr: `Faciliter la consommation de produits sains.`, answerCn: `促进健康食品消费。` },
          { id: 10, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T32", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Une sortie au théâtre.`, answerCn: `去剧院看戏。` },
          { id: 2, topicCn: "", answerFr: `D’un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 3, topicCn: "", answerFr: `La météo était très mauvaise.`, answerCn: `天气非常糟糕。` },
          { id: 4, topicCn: "", answerFr: `Leur salaire est insuffisant.`, answerCn: `他们的工资不足。` },
          { id: 5, topicCn: "", answerFr: `Les premiers mois d’un bébé.`, answerCn: `婴儿最初几个月。` },
          { id: 6, topicCn: "", answerFr: `Les gens cherchent davantage à être heureux.`, answerCn: `人们更加追求幸福。` },
          { id: 7, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 8, topicCn: "", answerFr: `Il pratique son art depuis l’enfance.`, answerCn: `他从小从事艺术。` },
          { id: 9, topicCn: "", answerFr: `De sensibiliser l’opinion.`, answerCn: `提高公众意识。` },
          { id: 10, topicCn: "", answerFr: `Adopter un mode de vie collectif responsable.`, answerCn: `采取负责任的集体生活方式。` },

          { type: "section", titleCn: "T33", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得不稳定。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `体育活动相关限制。` },
          { id: 4, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 5, topicCn: "", answerFr: `Le souci du bien-être des personnes hospitalisées.`, answerCn: `关注住院者福祉。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论所品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `S’exprimer avec précision.`, answerCn: `表达准确。` },
          { id: 8, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持积极态度。` },
          { id: 9, topicCn: "", answerFr: `Les habitudes alimentaires des élèves sont difficiles à modifier.`, answerCn: `学生饮食习惯难改变。` },
          { id: 10, topicCn: "", answerFr: `L’absence de formation à l’élaboration du budget.`, answerCn: `缺乏预算制定培训。` },

          { type: "section", titleCn: "T34", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Il fait plus beau qu’hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Ils annonçaient de fausses promotions.`, answerCn: `他们宣布虚假促销。` },
          { id: 4, topicCn: "", answerFr: `Il n’y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 5, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 6, topicCn: "", answerFr: `Amener l’élève à participer à sa propre formation.`, answerCn: `让学生参与自己的学习。` },
          { id: 7, topicCn: "", answerFr: `Ils partent à la montagne.`, answerCn: `他们去山里。` },
          { id: 8, topicCn: "", answerFr: `De son emploi du temps professionnel.`, answerCn: `关于他的职业时间安排。` },
          { id: 9, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门任务分配。` },
          { id: 10, topicCn: "", answerFr: `D’expérimenter une manière différente de voyager.`, answerCn: `尝试不同的旅行方式。` },

          { type: "section", titleCn: "T35", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 2, topicCn: "", answerFr: `Son œuvre est présentée en France.`, answerCn: `他的作品在法国展出。` },
          { id: 3, topicCn: "", answerFr: `Parce qu’ils ont été adoptés dans des pays différents.`, answerCn: `因为他们在不同国家被收养。` },
          { id: 4, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为休闲活动。` },
          { id: 5, topicCn: "", answerFr: `Elle a vite appris son métier.`, answerCn: `她很快学会自己的职业。` },
          { id: 6, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés.`, answerCn: `环境课程数量增加。` },
          { id: 7, topicCn: "", answerFr: `Elle permet à des jeunes d’habiter chez des personnes âgées.`, answerCn: `让年轻人与老人同住。` },
          { id: 8, topicCn: "", answerFr: `Il est protégé par des apports lexicaux variés.`, answerCn: `受到多样词汇保护。` },
          { id: 9, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门任务分配。` },
          { id: 10, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种帮助学习的工具。` },

          { type: "section", titleCn: "T36", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `La circulation routière est coupée.`, answerCn: `道路交通被中断。` },
          { id: 2, topicCn: "", answerFr: `Il est possible qu'il soit renvoyé.`, answerCn: `他可能会被解雇。` },
          { id: 3, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 4, topicCn: "", answerFr: `Il n’y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 5, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 6, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés.`, answerCn: `环境课程数量增加。` },
          { id: 7, topicCn: "", answerFr: `Elle permet à des jeunes d’habiter chez des personnes âgées.`, answerCn: `它让年轻人与老人同住。` },
          { id: 8, topicCn: "", answerFr: `Les avis qu'ils partagent au sujet de l'école.`, answerCn: `他们分享关于学校的看法。` },
          { id: 9, topicCn: "", answerFr: `Assister de façon discrète le client.`, answerCn: `低调地协助客户。` },
          { id: 10, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种无论学习什么学科都能帮助学习的工具。` },

          { type: "section", titleCn: "T37", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Le recrutement se fonde sur l'expérience.`, answerCn: `招聘基于经验。` },
          { id: 2, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 3, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为休闲活动。` },
          { id: 4, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业机会。` },
          { id: 5, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随伴侣。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论自己品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 8, topicCn: "", answerFr: `Des révisions d’un examen.`, answerCn: `准备考试复习。` },
          { id: 9, topicCn: "", answerFr: `Faciliter la consommation de produits sains.`, answerCn: `促进健康食品消费。` },
          { id: 10, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T38", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Une sortie au théâtre.`, answerCn: `去剧院看戏。` },
          { id: 2, topicCn: "", answerFr: `D’un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 3, topicCn: "", answerFr: `La météo était très mauvaise.`, answerCn: `天气非常糟糕。` },
          { id: 4, topicCn: "", answerFr: `Leur salaire est insuffisant.`, answerCn: `他们的工资不足。` },
          { id: 5, topicCn: "", answerFr: `Les premiers mois d’un bébé.`, answerCn: `婴儿最初几个月。` },
          { id: 6, topicCn: "", answerFr: `Les gens cherchent davantage à être heureux.`, answerCn: `人们更加追求幸福。` },
          { id: 7, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 8, topicCn: "", answerFr: `Il pratique son art depuis l’enfance.`, answerCn: `他从小从事艺术。` },
          { id: 9, topicCn: "", answerFr: `De sensibiliser l’opinion.`, answerCn: `提高公众意识。` },
          { id: 10, topicCn: "", answerFr: `Adopter un mode de vie collectif responsable.`, answerCn: `采取负责任的集体生活方式。` },

          { type: "section", titleCn: "T39", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得不稳定。` },
          { id: 2, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 3, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `体育活动相关限制。` },
          { id: 4, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 5, topicCn: "", answerFr: `Le souci du bien-être des personnes hospitalisées.`, answerCn: `关注住院者福祉。` },
          { id: 6, topicCn: "", answerFr: `Parler des plats que l’on savoure.`, answerCn: `谈论所品尝的菜肴。` },
          { id: 7, topicCn: "", answerFr: `S’exprimer avec précision.`, answerCn: `表达准确。` },
          { id: 8, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持积极态度。` },
          { id: 9, topicCn: "", answerFr: `Les habitudes alimentaires des élèves sont difficiles à modifier.`, answerCn: `学生饮食习惯难改变。` },
          { id: 10, topicCn: "", answerFr: `L’absence de formation à l’élaboration du budget.`, answerCn: `缺乏预算制定培训。` },

          { type: "section", titleCn: "T40", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 2, topicCn: "", answerFr: `D'un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 3, topicCn: "", answerFr: `Ils annonçaient de fausses promotions.`, answerCn: `他们宣布虚假促销。` },
          { id: 4, topicCn: "", answerFr: `Il n'y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 5, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 6, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés.`, answerCn: `环境课程数量增加。` },
          { id: 7, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 8, topicCn: "", answerFr: `Les avis qu'ils partagent au sujet de l'école.`, answerCn: `他们关于学校的看法。` },
          { id: 9, topicCn: "", answerFr: `Assister de façon discrète le client.`, answerCn: `低调协助客户。` },
          { id: 10, topicCn: "", answerFr: `D'un outil qui facilite l'apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种帮助学习的工具。` },


          { type: "section", titleCn: "新题", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `L’impact financier de la pollution sur les citoyens.`, answerCn: `污染对公民造成的经济影响。` },
          { id: 2, topicCn: "", answerFr: `D’avoir mal nourri son animal.`, answerCn: `没有好好喂养自己的动物。` },

"""

# ---- Config ----
TACHE = 2             # change to 2/3 if you want
KIND = "a"               # "a" for answers; if you insist, change to "q"
OUT_CSV = Path("assets/tcfcaCO/t2.csv")
# ----------------

import re

def extract_answerfr_strings(text: str) -> list[str]:
    # matches: answerFr: `...`   OR   answerFr: "..."
    pat = re.compile(
        r'answerFr\s*:\s*(?:`(?P<bt>[\s\S]*?)`|"(?P<dq>(?:\\.|[^"\\])*)")'
    )

    answers = []
    for m in pat.finditer(text):
        s = m.group("bt") if m.group("bt") is not None else m.group("dq")
        # if it's the "..." form, unescape (optional but nice)
        if m.group("dq") is not None:
            s = bytes(s, "utf-8").decode("unicode_escape")
        s = (s or "").strip()
        if s:
            answers.append(s)
    return answers


def main():
    answers = extract_answerfr_strings(RAW_JS)

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(["tache", "kind", "idx", "text"])  # 4 columns
        for idx, sentence in enumerate(answers, start=1):
            w.writerow([TACHE, KIND, idx, sentence])

    print("Exported:", OUT_CSV)
    print("Count:", len(answers))


if __name__ == "__main__":
    main()
