#!/usr/bin/env python3
import csv
from pathlib import Path

# Paste your JS-style array BELOW, exactly as-is (keys unquoted like id:, topicCn:, answerFr:, etc.)
RAW_JS = r"""
[
          { type: "section", titleCn: "T1", descFr: "", descCn: "" },
          { id: 1, topicCn: "", answerFr: `De réserver un livre.`, answerCn: `预订一本书。` },
          { id: 2, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 3, topicCn: "", answerFr: `La promotion d'un moyen d'échanges entre les différentes nationalités.`, answerCn: `促进不同国籍之间交流的方式。` },
          { id: 4, topicCn: "", answerFr: `Elles se rebellent très vite face à l'autorité familiale au quotidien.`, answerCn: `她们在日常生活中很快反抗家庭权威。` },
          { id: 5, topicCn: "", answerFr: `Découvrir une région de France.`, answerCn: `探索法国的一个地区。` },
          { id: 6, topicCn: "", answerFr: `Pour se réchauffer.`, answerCn: `为了取暖。` },
          { id: 7, topicCn: "", answerFr: `Elle a arrêté d'exercer sa profession.`, answerCn: `她停止从事自己的职业。` },
          { id: 8, topicCn: "", answerFr: `La musique.`, answerCn: `音乐。` },
          { id: 9, topicCn: "", answerFr: `Elle a travaillé avec une institutrice américaine.`, answerCn: `她曾与一位美国女教师合作。` },
          { id: 10, topicCn: "", answerFr: `D'un appel à projets imaginaires.`, answerCn: `来自一次虚构项目征集。` },

          { type: "section", titleCn: "T2", descFr: "", descCn: "" },
          { id: 11, topicCn: "", answerFr: `La circulation routière est coupée.`, answerCn: `道路交通被中断。` },
          { id: 12, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 13, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 14, topicCn: "", answerFr: `Ils déplorent un manque d'information.`, answerCn: `他们对信息不足表示遗憾。` },
          { id: 15, topicCn: "", answerFr: `Le stationnement est devenu payant.`, answerCn: `停车现在变成收费的。` },
          { id: 16, topicCn: "", answerFr: `La variété de la programmation.`, answerCn: `节目安排的多样性。` },
          { id: 17, topicCn: "", answerFr: `La recherche d'un appartement est rapide.`, answerCn: `寻找公寓的过程很快。` },
          { id: 18, topicCn: "", answerFr: `Parce qu'elles avaient lieu tôt dans l'année scolaire.`, answerCn: `因为它们发生在学年初期。` },
          { id: 19, topicCn: "", answerFr: `L'état actuel de la biodiversité.`, answerCn: `当前的生物多样性状况。` },
          { id: 20, topicCn: "", answerFr: `D'expérimenter une manière différente de voyager.`, answerCn: `尝试一种不同的旅行方式。` },

          { type: "section", titleCn: "T3", descFr: "", descCn: "" },
          { id: 21, topicCn: "", answerFr: `Un de ses enfants a du mal à respecter les règles du jeu.`, answerCn: `他的一个孩子难以遵守游戏规则。` },
          { id: 22, topicCn: "", answerFr: `De se montrer prudent.`, answerCn: `表现得谨慎。` },
          { id: 23, topicCn: "", answerFr: `La mutation de l'habitat des abeilles.`, answerCn: `蜜蜂栖息地的变化。` },
          { id: 24, topicCn: "", answerFr: `La mobilité.`, answerCn: `流动性。` },
          { id: 25, topicCn: "", answerFr: `Il offre des services de qualité supérieure.`, answerCn: `他提供高质量服务。` },
          { id: 26, topicCn: "", answerFr: `Elle a d'abord une vocation caritative.`, answerCn: `她最初有慈善使命。` },
          { id: 27, topicCn: "", answerFr: `Il faut prouver la nécessité de la démarche.`, answerCn: `必须证明这一行动的必要性。` },
          { id: 28, topicCn: "", answerFr: `Il pense qu'il aurait dû être prévenu.`, answerCn: `他认为本应有人通知他。` },
          { id: 29, topicCn: "", answerFr: `Les critères de sélection sont particulièrement stricts.`, answerCn: `选拔标准非常严格。` },
          { id: 30, topicCn: "", answerFr: `De maigrir plus rapidement.`, answerCn: `更快地减肥。` },

          { type: "section", titleCn: "T4", descFr: "", descCn: "" },
          { id: 31, topicCn: "", answerFr: `Il s'adresse aux acheteurs à Noël.`, answerCn: `他面向圣诞节购物者。` },
          { id: 32, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 33, topicCn: "", answerFr: `L'absence de vérification des sources.`, answerCn: `缺乏对信息来源的核实。` },
          { id: 34, topicCn: "", answerFr: `Parce qu'elle souffre et qu'elle est fatiguée.`, answerCn: `因为她感到痛苦和疲惫。` },
          { id: 35, topicCn: "", answerFr: `D'une sélection de films.`, answerCn: `一系列电影的选择。` },
          { id: 36, topicCn: "", answerFr: `Il veut éviter toute publicité personnelle.`, answerCn: `他想避免任何个人宣传。` },
          { id: 37, topicCn: "", answerFr: `Il avait du mal à accepter ses choix.`, answerCn: `他难以接受自己的选择。` },
          { id: 38, topicCn: "", answerFr: `La création d'un livre pour enfant de qualité est un travail d'équipe.`, answerCn: `制作高质量儿童书是团队合作。` },
          { id: 39, topicCn: "", answerFr: `Des comportements alimentaires.`, answerCn: `饮食行为。` },
          { id: 40, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T5", descFr: "", descCn: "" },
          { id: 41, topicCn: "", answerFr: `Le recrutement se fonde sur l'expérience.`, answerCn: `招聘以经验为基础。` },
          { id: 42, topicCn: "", answerFr: `Les travaux nécessaires ne sont pas encore achevés.`, answerCn: `必要工程尚未完成。` },
          { id: 43, topicCn: "", answerFr: `Des activités en faveur du développement durable.`, answerCn: `支持可持续发展的活动。` },
          { id: 44, topicCn: "", answerFr: `Comment recycler son sapin ?`, answerCn: `如何回收圣诞树？` },
          { id: 45, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随伴侣。` },
          { id: 46, topicCn: "", answerFr: `Ils osent davantage partir à l'étranger qu'auparavant.`, answerCn: `他们比以前更敢出国。` },
          { id: 47, topicCn: "", answerFr: `Un récit autobiographique ancré dans la vie intellectuelle du siècle dernier.`, answerCn: `一部扎根于上世纪知识生活的自传。` },
          { id: 48, topicCn: "", answerFr: `De son emploi du temps professionnel.`, answerCn: `关于他的职业时间安排。` },
          { id: 49, topicCn: "", answerFr: `Elle est restée toute seule.`, answerCn: `她一直独自一人。` },
          { id: 50, topicCn: "", answerFr: `Sa fréquentation des salles dès son plus jeune âge.`, answerCn: `她从很小就经常去这些场所。` },

          { type: "section", titleCn: "T6", descFr: "", descCn: "" },
          { id: 51, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得脆弱。` },
          { id: 52, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 53, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 54, topicCn: "", answerFr: `Des formules adaptées à chaque client.`, answerCn: `为每位客户量身定制的方案。` },
          { id: 55, topicCn: "", answerFr: `L'ouverture de formations artistiques.`, answerCn: `开设艺术培训课程。` },
          { id: 56, topicCn: "", answerFr: `Privilégier une agriculture sans produit chimique.`, answerCn: `优先发展无化学品农业。` },
          { id: 57, topicCn: "", answerFr: `Le confort que leur procure leur structure familiale.`, answerCn: `家庭结构带给他们的安全感。` },
          { id: 58, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持积极态度。` },
          { id: 59, topicCn: "", answerFr: `Son parcours d'apprentissage.`, answerCn: `他的学习经历。` },
          { id: 60, topicCn: "", answerFr: `D'élargir sa recherche d'emploi à d'autres domaines.`, answerCn: `把求职范围扩大到其他领域。` },

          { type: "section", titleCn: "T7", descFr: "", descCn: "" },
          { id: 61, topicCn: "", answerFr: `La nécessité de trouver un travail.`, answerCn: `需要找到一份工作。` },
          { id: 62, topicCn: "", answerFr: `Elle conseille une activité physique.`, answerCn: `她建议进行体育活动。` },
          { id: 63, topicCn: "", answerFr: `Des activités en faveur du développement durable.`, answerCn: `促进可持续发展的活动。` },
          { id: 64, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 65, topicCn: "", answerFr: `Des formules adaptées à chaque client.`, answerCn: `适合每个客户的方案。` },
          { id: 66, topicCn: "", answerFr: `Parce qu'elle souhaite changer de destination estivale.`, answerCn: `因为她想换一个夏季度假地。` },
          { id: 67, topicCn: "", answerFr: `En collaborant à des activités de bénévolat.`, answerCn: `通过参与志愿活动。` },
          { id: 68, topicCn: "", answerFr: `Ils sont cultivés par des gens sans emploi.`, answerCn: `它们由失业者种植。` },
          { id: 69, topicCn: "", answerFr: `Son parcours d'apprentissage.`, answerCn: `他的学习历程。` },
          { id: 70, topicCn: "", answerFr: `Ils devront demander le remboursement de leur billet par écrit.`, answerCn: `他们必须书面申请退票。` },

          { type: "section", titleCn: "T8", descFr: "", descCn: "" },
          { id: 71, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天好。` },
          { id: 72, topicCn: "", answerFr: `Les écologistes refusent la construction d'une autoroute.`, answerCn: `环保人士反对修建高速公路。` },
          { id: 73, topicCn: "", answerFr: `Pour être autonome face aux petits travaux de la maison.`, answerCn: `为了能自己处理家庭小维修。` },
          { id: 74, topicCn: "", answerFr: `Un point de vue sur la situation mondiale aujourd'hui.`, answerCn: `对当今世界局势的观点。` },
          { id: 75, topicCn: "", answerFr: `De partager sa salle de bain.`, answerCn: `共用浴室。` },
          { id: 76, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样的课程教育。` },
          { id: 77, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有做自己老板的自由。` },
          { id: 78, topicCn: "", answerFr: `Des comportements alimentaires.`, answerCn: `饮食行为。` },
          { id: 79, topicCn: "", answerFr: `D'élargir sa recherche d'emploi à d'autres domaines.`, answerCn: `扩大求职领域。` },
          { id: 80, topicCn: "", answerFr: `L'utilisation d'un matériau unique.`, answerCn: `使用单一材料。` },

          { type: "section", titleCn: "T9", descFr: "", descCn: "" },
          { id: 81, topicCn: "", answerFr: `Il est possible qu'il soit renvoyé.`, answerCn: `他有可能被解雇。` },
          { id: 82, topicCn: "", answerFr: `Elle travaille dans un restaurant.`, answerCn: `她在一家餐馆工作。` },
          { id: 83, topicCn: "", answerFr: `Elle est terrorisée par les animaux aquatiques.`, answerCn: `她害怕水生动物。` },
          { id: 84, topicCn: "", answerFr: `Pour plonger dans l'imaginaire.`, answerCn: `为了沉浸在想象世界。` },
          { id: 85, topicCn: "", answerFr: `Elle a été impressionnée par le son des cordes qu'on peut faire vibrer longtemps.`, answerCn: `她被能长时间震动的弦乐声音打动。` },
          { id: 86, topicCn: "", answerFr: `Parce que la consommation dépend avant tout du pouvoir d'achat.`, answerCn: `因为消费首先取决于购买力。` },
          { id: 87, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 88, topicCn: "", answerFr: `Il diminue les efforts de ceux qui le suivent.`, answerCn: `它减少后来者的努力。` },
          { id: 89, topicCn: "", answerFr: `Elles ont la notion du temps chronologique.`, answerCn: `她们具有时间顺序概念。` },
          { id: 90, topicCn: "", answerFr: `Expliquer pourquoi on attend de la musique au lieu des programmes habituels.`, answerCn: `解释为什么播放音乐而不是正常节目。` },

          { type: "section", titleCn: "T10", descFr: "", descCn: "" },
          { id: 91, topicCn: "", answerFr: `Visiter une ville.`, answerCn: `参观一座城市。` },
          { id: 92, topicCn: "", answerFr: `Le secrétariat de son département.`, answerCn: `他所在部门的秘书处。` },
          { id: 93, topicCn: "", answerFr: `Ils jouent aux cartes.`, answerCn: `他们在打牌。` },
          { id: 94, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `体育活动相关限制。` },
          { id: 95, topicCn: "", answerFr: `Elles se rebellent très vite face à l'autorité familiale au quotidien.`, answerCn: `她们日常生活中很快反抗家庭权威。` },
          { id: 96, topicCn: "", answerFr: `Il a travaillé dans un commerce.`, answerCn: `他曾在一家商店工作。` },
          { id: 97, topicCn: "", answerFr: `Il s'est d'abord fait connaître auprès des étudiants.`, answerCn: `他最初在学生中出名。` },
          { id: 98, topicCn: "", answerFr: `En les incitant à travailler de manière collaborative.`, answerCn: `通过鼓励他们合作学习。` },
          { id: 99, topicCn: "", answerFr: `Établir un certificat médical.`, answerCn: `开具医疗证明。` },
          { id: 100, topicCn: "", answerFr: `L'implication active de tous les habitants.`, answerCn: `所有居民的积极参与。` },

          { type: "section", titleCn: "T11", descFr: "", descCn: "" },
          { id: 101, topicCn: "", answerFr: `Les conditions de recrutement sont plus difficiles aujourd'hui.`, answerCn: `如今招聘条件更加困难。` },
          { id: 102, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 103, topicCn: "", answerFr: `D'attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为一种休闲活动。` },
          { id: 104, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业发展的机会。` },
          { id: 105, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随她的伴侣。` },
          { id: 106, topicCn: "", answerFr: `Parler des plats que l'on savoure.`, answerCn: `谈论自己品尝的菜肴。` },
          { id: 107, topicCn: "", answerFr: `Avoir la liberté d'être son propre patron.`, answerCn: `拥有做自己老板的自由。` },
          { id: 108, topicCn: "", answerFr: `Des révisions d'un examen.`, answerCn: `准备一场考试复习。` },
          { id: 109, topicCn: "", answerFr: `Faciliter la consommation de produits sains.`, answerCn: `促进健康食品消费。` },
          { id: 110, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T12", descFr: "", descCn: "" },
          { id: 111, topicCn: "", answerFr: `Une sortie au théâtre.`, answerCn: `去剧院看戏。` },
          { id: 112, topicCn: "", answerFr: `D'un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 113, topicCn: "", answerFr: `La météo était très mauvaise.`, answerCn: `天气非常糟糕。` },
          { id: 114, topicCn: "", answerFr: `Leur salaire est insuffisant.`, answerCn: `他们的工资不足。` },
          { id: 115, topicCn: "", answerFr: `Les premiers mois d'un bébé.`, answerCn: `婴儿最初几个月。` },
          { id: 116, topicCn: "", answerFr: `Les gens cherchent davantage à être heureux.`, answerCn: `人们更加追求幸福。` },
          { id: 117, topicCn: "", answerFr: `La création de meubles à partir du recyclage.`, answerCn: `用回收材料制作家具。` },
          { id: 118, topicCn: "", answerFr: `Il pratique son art depuis l'enfance.`, answerCn: `他从小就从事自己的艺术。` },
          { id: 119, topicCn: "", answerFr: `De sensibiliser l'opinion.`, answerCn: `提高公众意识。` },
          { id: 120, topicCn: "", answerFr: `Adopter un mode de vie collectif responsable.`, answerCn: `采取负责任的集体生活方式。` },

          { type: "section", titleCn: "T13", descFr: "", descCn: "" },
          { id: 121, topicCn: "", answerFr: `Leurs financements sont fragilisés.`, answerCn: `他们的资金来源变得不稳定。` },
          { id: 122, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 123, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives.`, answerCn: `与体育活动相关的限制。` },
          { id: 124, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 125, topicCn: "", answerFr: `Le souci du bien-être des personnes hospitalisées.`, answerCn: `关注住院者的福祉。` },
          { id: 126, topicCn: "", answerFr: `Parler des plats que l'on savoure.`, answerCn: `谈论所品尝的菜肴。` },
          { id: 127, topicCn: "", answerFr: `S'exprimer avec précision.`, answerCn: `表达准确。` },
          { id: 128, topicCn: "", answerFr: `Ils voient leur futur de manière positive.`, answerCn: `他们对未来持乐观态度。` },
          { id: 129, topicCn: "", answerFr: `Les habitudes alimentaires des élèves sont difficiles à modifier.`, answerCn: `学生的饮食习惯难以改变。` },
          { id: 130, topicCn: "", answerFr: `L'absence de formation à l'élaboration du budget.`, answerCn: `缺乏预算制定培训。` },

          { type: "section", titleCn: "T14", descFr: "", descCn: "" },
          { id: 131, topicCn: "", answerFr: `Il fait plus beau qu'hier.`, answerCn: `今天天气比昨天更好。` },
          { id: 132, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 133, topicCn: "", answerFr: `Ils annonçaient de fausses promotions.`, answerCn: `他们宣布虚假的促销。` },
          { id: 134, topicCn: "", answerFr: `Il n'y a plus de place pour la voiture.`, answerCn: `已经没有停车位。` },
          { id: 135, topicCn: "", answerFr: `Elle a suivi des enseignements variés.`, answerCn: `她接受了多样课程教育。` },
          { id: 136, topicCn: "", answerFr: `Amener l'élève à participer à sa propre formation.`, answerCn: `让学生参与自己的学习。` },
          { id: 137, topicCn: "", answerFr: `Ils partent à la montagne.`, answerCn: `他们去山里。` },
          { id: 138, topicCn: "", answerFr: `De son emploi du temps professionnel.`, answerCn: `关于他的职业时间安排。` },
          { id: 139, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门中的任务分配。` },
          { id: 140, topicCn: "", answerFr: `D'expérimenter une manière différente de voyager.`, answerCn: `尝试不同的旅行方式。` },

          { type: "section", titleCn: "T15", descFr: "", descCn: "" },
          { id: 141, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 142, topicCn: "", answerFr: `Son œuvre est présentée en France.`, answerCn: `他的作品在法国展出。` },
          { id: 143, topicCn: "", answerFr: `Parce qu'ils ont été adoptés dans des pays différents.`, answerCn: `因为他们在不同国家被收养。` },
          { id: 144, topicCn: "", answerFr: `D'attribuer à la lecture le statut de loisir.`, answerCn: `把阅读视为休闲活动。` },
          { id: 145, topicCn: "", answerFr: `Elle a vite appris son métier.`, answerCn: `她很快学会了自己的职业。` },
          { id: 146, topicCn: "", answerFr: `Les cursus sur l'environnement se sont multipliés.`, answerCn: `环境课程数量增加。` },
          { id: 147, topicCn: "", answerFr: `Elle permet à des jeunes d'habiter chez des personnes âgées.`, answerCn: `它让年轻人与老人同住。` },
          { id: 148, topicCn: "", answerFr: `Il est protégé par des apports lexicaux variés.`, answerCn: `它受到多样词汇的保护。` },
          { id: 149, topicCn: "", answerFr: `La répartition des tâches dans le service.`, answerCn: `部门任务分配。` },
          { id: 150, topicCn: "", answerFr: `D'un outil qui facilite l'apprentissage quelle que soit la discipline étudiée.`, answerCn: `一种无论学习什么学科都能帮助学习的工具。` },

          { type: "section", titleCn: "T16", descFr: "", descCn: "" },
          { id: 151, topicCn: "", answerFr: `D’une campagne d’action sociale`, answerCn: `一场社会行动宣传活动` },
          { id: 152, topicCn: "", answerFr: `La circulation routière est coupée`, answerCn: `道路交通被切断了` },
          { id: 153, topicCn: "", answerFr: `La promotion d’un moyen d’échanges entre les différentes nationalités`, answerCn: `推广一种不同国籍之间交流的方式` },
          { id: 154, topicCn: "", answerFr: `A un poste de responsabilité du village`, answerCn: `担任村里的一个负责岗位` },
          { id: 155, topicCn: "", answerFr: `Pour affirmer notre personnalité`, answerCn: `为了彰显我们的个性` },
          { id: 156, topicCn: "", answerFr: `Elle permet à des jeunes d’habiter chez des personnes âgées`, answerCn: `它让年轻人住到老年人家中` },
          { id: 157, topicCn: "", answerFr: `La sociabilité à l'ère du numérique`, answerCn: `数字时代的社交性` },
          { id: 158, topicCn: "", answerFr: `D’éviter des pertes de temps`, answerCn: `为了避免浪费时间` },
          { id: 159, topicCn: "", answerFr: `La répartition des taches dans le service`, answerCn: `部门内任务的分配` },
          { id: 160, topicCn: "", answerFr: `L’absence de formation sur l’élaboration d’un budget`, answerCn: `缺乏关于编制预算的培训` },

          { type: "section", titleCn: "T17", descFr: "", descCn: "" },
          { id: 161, topicCn: "", answerFr: `C’est plus simple`, answerCn: `这样更简单` },
          { id: 162, topicCn: "", answerFr: `Les conditions météoritiques`, answerCn: `气象条件` },
          { id: 163, topicCn: "", answerFr: `La météo était très mauvaise`, answerCn: `天气非常糟糕` },
          { id: 164, topicCn: "", answerFr: `De procédés de recyclage`, answerCn: `回收利用的方法` },
          { id: 165, topicCn: "", answerFr: `Pour affirmer notre personnalité`, answerCn: `为了彰显我们的个性` },
          { id: 166, topicCn: "", answerFr: `Ils sont réalisés avec des objets recyclés`, answerCn: `它们是用回收物品制成的` },
          { id: 167, topicCn: "", answerFr: `Pour obtenir une information`, answerCn: `为了获取一条信息` },
          { id: 168, topicCn: "", answerFr: `En les incitant à travailler de manière collaborative`, answerCn: `通过鼓励他们以协作的方式工作` },
          { id: 169, topicCn: "", answerFr: `Des comportements alimentaires`, answerCn: `饮食行为` },
          { id: 170, topicCn: "", answerFr: `L’utilisation d’un matériau unique`, answerCn: `使用单一材料` },

          { type: "section", titleCn: "T18", descFr: "", descCn: "" },
          { id: 171, topicCn: "", answerFr: `Élargir les connaissances scientifiques des participants`, answerCn: `扩大参与者的科学知识` },
          { id: 172, topicCn: "", answerFr: `De l’étonnement`, answerCn: `惊讶` },
          { id: 173, topicCn: "", answerFr: `Les contraintes liées aux pratiques sportives`, answerCn: `与体育活动相关的限制` },
          { id: 174, topicCn: "", answerFr: `Pour lui fixer un entretien d’embauche`, answerCn: `为了给他安排一场求职面试` },
          { id: 175, topicCn: "", answerFr: `Il offre des services de qualité supérieure`, answerCn: `它提供高质量的服务` },
          { id: 176, topicCn: "", answerFr: `Une paire de lunettes`, answerCn: `一副眼镜` },
          { id: 177, topicCn: "", answerFr: `Avoir vécu dans le pays de la langue qu’ils enseignent`, answerCn: `曾在他们所教授语言对应的国家生活过` },
          { id: 178, topicCn: "", answerFr: `Du système français de taxe d’habitation`, answerCn: `法国住房税制度` },
          { id: 179, topicCn: "", answerFr: `Une croisière-promenade sur la Seine`, answerCn: `一次塞纳河游船观光` },
          { id: 180, topicCn: "", answerFr: `Ils devront demander le remboursement de leur billet par écrit`, answerCn: `他们必须以书面形式申请退票` },

          { type: "section", titleCn: "T19", descFr: "", descCn: "" },
          { id: 181, topicCn: "", answerFr: `Le voyage est trop long`, answerCn: `旅程太长了` },
          { id: 182, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 183, topicCn: "", answerFr: `La météo était très mauvaise`, answerCn: `天气非常糟糕` },
          { id: 184, topicCn: "", answerFr: `La construction de villes sur l’eau`, answerCn: `在水上建造城市` },
          { id: 185, topicCn: "", answerFr: `Une information complète pour le consommateur`, answerCn: `为消费者提供完整的信息` },
          { id: 186, topicCn: "", answerFr: `A l’époque de sa jeunesse`, answerCn: `在他年轻的时候` },
          { id: 187, topicCn: "", answerFr: `Il avait du mal à accepter ses choix`, answerCn: `他很难接受自己的选择` },
          { id: 188, topicCn: "", answerFr: `Pour éviter les sollicitations abusives`, answerCn: `为了避免骚扰式招揽` },
          { id: 189, topicCn: "", answerFr: `Etablir un certificat médical`, answerCn: `开具一份医疗证明` },
          { id: 190, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage, quelle que soit la discipline étudiée`, answerCn: `一种无论学习什么学科都能促进学习的工具` },

          { type: "section", titleCn: "T20", descFr: "", descCn: "" },
          { id: 191, topicCn: "", answerFr: `Elle a décidé de changer d’emballage`, answerCn: `她决定更换包装` },
          { id: 192, topicCn: "", answerFr: `De renforcer les relations`, answerCn: `加强彼此关系` },
          { id: 193, topicCn: "", answerFr: `La météo était très mauvaise`, answerCn: `天气非常糟糕` },
          { id: 194, topicCn: "", answerFr: `De procédés de recyclage`, answerCn: `回收利用的方法` },
          { id: 195, topicCn: "", answerFr: `Amener l’élève à participer à sa propre formation`, answerCn: `让学生参与到自己的学习过程中` },
          { id: 196, topicCn: "", answerFr: `Le report de la remise d’un devoir`, answerCn: `推迟提交一项作业` },
          { id: 197, topicCn: "", answerFr: `Renforcer la formation numérique des jeunes`, answerCn: `加强年轻人的数字技能培训` },
          { id: 198, topicCn: "", answerFr: `Elle reflète une vision sexiste de la société`, answerCn: `它反映了一种带有性别歧视的社会观念` },
          { id: 199, topicCn: "", answerFr: `Aider les consommateurs à mieux acheter`, answerCn: `帮助消费者更好地购物` },
          { id: 200, topicCn: "", answerFr: `D’élargir sa recherche d’emploi à d’autres domaines`, answerCn: `把求职范围扩大到其他领域` },

          { type: "section", titleCn: "T21", descFr: "", descCn: "" },
          { id: 201, topicCn: "", answerFr: `Elle trouve le vent trop fort`, answerCn: `她觉得风太大了` },
          { id: 202, topicCn: "", answerFr: `D’un projet de voyage`, answerCn: `关于一个旅行计划` },
          { id: 203, topicCn: "", answerFr: `Leur salaire est insuffisant`, answerCn: `他们的工资不够` },
          { id: 204, topicCn: "", answerFr: `Les équipements`, answerCn: `设备` },
          { id: 205, topicCn: "", answerFr: `Il veut éviter toute publicité personnelle`, answerCn: `他想避免任何针对个人的宣传` },
          { id: 206, topicCn: "", answerFr: `Diffuser des procédés en accord avec la nature`, answerCn: `传播与自然相协调的方法` },
          { id: 207, topicCn: "", answerFr: `Des révisions d’un examen`, answerCn: `考试复习` },
          { id: 208, topicCn: "", answerFr: `Se rendre à une vente de livres universitaires d’occasion à la faculté`, answerCn: `去学院参加一次二手大学书籍售卖活动` },
          { id: 209, topicCn: "", answerFr: `Elle est restée toute seule`, answerCn: `她独自一人留下了` },
          { id: 210, topicCn: "", answerFr: `Une ascension professionnelle accompagnée de revenus confortables`, answerCn: `伴随着可观收入的职业晋升` },

          { type: "section", titleCn: "T22", descFr: "", descCn: "" },
          { id: 211, topicCn: "", answerFr: `Il travaille pour plusieurs entreprises`, answerCn: `他为多家公司工作` },
          { id: 212, topicCn: "", answerFr: `L’implication des professionnels de la gastronomie`, answerCn: `餐饮业专业人士的参与` },
          { id: 213, topicCn: "", answerFr: `Que l’homme se soit mis à faire du sport`, answerCn: `那个男人开始做运动了` },
          { id: 214, topicCn: "", answerFr: `La promotion d’un moyen d’échanges entre les différentes nationalités`, answerCn: `推广一种不同国籍之间交流的方式` },
          { id: 215, topicCn: "", answerFr: `Ils déplorent un manque d’information`, answerCn: `他们对信息不足表示遗憾` },
          { id: 216, topicCn: "", answerFr: `Quelqu’un qui invente de nouveaux termes`, answerCn: `一个创造新词的人` },
          { id: 217, topicCn: "", answerFr: `Parce qu’il manque du personnel aujourd’hui`, answerCn: `因为如今缺少工作人员` },
          { id: 218, topicCn: "", answerFr: `Il avait du mal à accepter ses choix`, answerCn: `他很难接受自己的选择` },
          { id: 219, topicCn: "", answerFr: `Parce qu’elles ont beaucoup à apprendre d’eux`, answerCn: `因为她们有很多东西要向他们学习` },
          { id: 220, topicCn: "", answerFr: `Elle prépare une opération commerciale`, answerCn: `她正在筹备一次商业促销活动` },

          { type: "section", titleCn: "T23", descFr: "", descCn: "" },
          { id: 221, topicCn: "", answerFr: `Manger au restaurant`, answerCn: `在餐馆吃饭` },
          { id: 222, topicCn: "", answerFr: `Les conditions météorologiques`, answerCn: `气象条件` },
          { id: 223, topicCn: "", answerFr: `Il est ironique`, answerCn: `他很讽刺` },
          { id: 224, topicCn: "", answerFr: `Leur salaire est insuffisant`, answerCn: `他们的工资不够` },
          { id: 225, topicCn: "", answerFr: `Le stationnement est devenu payant`, answerCn: `停车已经变成收费的了` },
          { id: 226, topicCn: "", answerFr: `Un mois`, answerCn: `一个月` },
          { id: 227, topicCn: "", answerFr: `La recherche d’un appartement est rapide`, answerCn: `找公寓很快` },
          { id: 228, topicCn: "", answerFr: `Il pratique son art depuis l’enfance`, answerCn: `他从小就从事自己的艺术` },
          { id: 229, topicCn: "", answerFr: `Elles ont la notion du temps chronologique`, answerCn: `她们具有时间先后顺序的概念` },
          { id: 230, topicCn: "", answerFr: `S’extraire du quotidien`, answerCn: `从日常生活中抽离出来` },

          { type: "section", titleCn: "T24", descFr: "", descCn: "" },
          { id: 231, topicCn: "", answerFr: `De partir à l’étranger`, answerCn: `去国外` },
          { id: 232, topicCn: "", answerFr: `Tourner un film`, answerCn: `拍摄一部电影` },
          { id: 233, topicCn: "", answerFr: `Il est ironique`, answerCn: `他很讽刺` },
          { id: 234, topicCn: "", answerFr: `Pour lui fixer un entretien d’embauche`, answerCn: `为了给他安排一场求职面试` },
          { id: 235, topicCn: "", answerFr: `Pour se réchauffer`, answerCn: `为了取暖` },
          { id: 236, topicCn: "", answerFr: `Privilégier une agriculture sans produit chimique`, answerCn: `优先发展不使用化学产品的农业` },
          { id: 237, topicCn: "", answerFr: `Il faut prouver la nécessité de la démarche`, answerCn: `必须证明这项做法的必要性` },
          { id: 238, topicCn: "", answerFr: `Une croisière promenade sur la Seine`, answerCn: `一次塞纳河游船观光` },
          { id: 239, topicCn: "", answerFr: `La répartition des tâches dans le service`, answerCn: `部门内任务的分配` },
          { id: 240, topicCn: "", answerFr: `Expliquer pourquoi on attend de la musique au lieu des programmes habituels`, answerCn: `解释为什么播放的是音乐而不是平常的节目` },

          { type: "section", titleCn: "T25", descFr: "", descCn: "" },
          { id: 241, topicCn: "", answerFr: `L’affiche.`, answerCn: `海报。` },
          { id: 242, topicCn: "", answerFr: `D’un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 243, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 244, topicCn: "", answerFr: `De partager sa salle de bain.`, answerCn: `共用他的浴室。` },
          { id: 245, topicCn: "", answerFr: `Ils choisissent de partager leur habitation avec des jeunes.`, answerCn: `他们选择与年轻人共享住房。` },
          { id: 246, topicCn: "", answerFr: `Ils ignorent l’origine de leurs plats.`, answerCn: `他们不知道自己菜肴的来源。` },
          { id: 247, topicCn: "", answerFr: `D’avoir choisi d’y aller seul.`, answerCn: `因为选择独自去那里。` },
          { id: 248, topicCn: "", answerFr: `À s’occuper du gâteau d’anniversaire.`, answerCn: `负责准备生日蛋糕。` },
          { id: 249, topicCn: "", answerFr: `Une ascension professionnelle accompagnée de revenus confortables.`, answerCn: `伴随着可观收入的职业晋升。` },
          { id: 250, topicCn: "", answerFr: `Une naissance.`, answerCn: `一次出生。` },

          { type: "section", titleCn: "T26", descFr: "", descCn: "" },
          { id: 251, topicCn: "", answerFr: `De réviser les méthodes pédagogiques actuelles`, answerCn: `修订当前的教学方法` },
          { id: 252, topicCn: "", answerFr: `Elle voyage souvent`, answerCn: `她经常旅行` },
          { id: 253, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir`, answerCn: `把阅读视为一种休闲活动` },
          { id: 254, topicCn: "", answerFr: `Comment recycler son sapin`, answerCn: `如何回收利用自己的圣诞树` },
          { id: 255, topicCn: "", answerFr: `Elle leur permet de se loger en toute sécurité`, answerCn: `它让他们能够安全地住宿` },
          { id: 256, topicCn: "", answerFr: `Amener l’élève à participer à sa propre formation`, answerCn: `让学生参与到自己的学习过程中` },
          { id: 257, topicCn: "", answerFr: `Elle est respectée pour son professionnalisme`, answerCn: `她因其专业素养而受到尊重` },
          { id: 258, topicCn: "", answerFr: `Ils apprennent à communiquer`, answerCn: `他们学会沟通` },
          { id: 259, topicCn: "", answerFr: `Faciliter la consommation de produits sains`, answerCn: `促进健康产品的消费` },
          { id: 260, topicCn: "", answerFr: `D’une sensibilisation aux injustices`, answerCn: `对不公正现象的一种觉察` },

          { type: "section", titleCn: "T27", descFr: "", descCn: "" },
          { id: 261, topicCn: "", answerFr: `La circulation routière est coupée`, answerCn: `道路交通被中断了` },
          { id: 262, topicCn: "", answerFr: `De renforcer les relations`, answerCn: `加强彼此关系` },
          { id: 263, topicCn: "", answerFr: `Parce que la famille a des revenus irréguliers`, answerCn: `因为这个家庭的收入不稳定` },
          { id: 264, topicCn: "", answerFr: `À un poste de responsable du village`, answerCn: `担任村里的一个负责人职位` },
          { id: 265, topicCn: "", answerFr: `Elle a d’abord une vocation caritative`, answerCn: `它首先具有慈善性质` },
          { id: 266, topicCn: "", answerFr: `Il dénonce la stérilité des affrontements`, answerCn: `他谴责这些对抗的徒劳无益` },
          { id: 267, topicCn: "", answerFr: `Vérifier les caractéristiques des aliments`, answerCn: `核查食品的特性` },
          { id: 268, topicCn: "", answerFr: `Elle reflète une vision sexiste de la société`, answerCn: `它反映了一种带有性别歧视的社会观念` },
          { id: 269, topicCn: "", answerFr: `Les habitudes alimentaires des élèves sont difficiles à modifier`, answerCn: `学生的饮食习惯很难改变` },
          { id: 270, topicCn: "", answerFr: `Il s’apparente à un effort physique`, answerCn: `它类似于一种体力劳动` },

          { type: "section", titleCn: "T28", descFr: "", descCn: "" },
          { id: 271, topicCn: "", answerFr: `Elle a décidé de changer d’emballage`, answerCn: `她决定更换包装` },
          { id: 272, topicCn: "", answerFr: `D’un projet de voyage`, answerCn: `关于一个旅行计划` },
          { id: 273, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir`, answerCn: `把阅读赋予一种休闲活动的地位` },
          { id: 274, topicCn: "", answerFr: `Elle a vite appris son métier`, answerCn: `她很快学会了自己的职业` },
          { id: 275, topicCn: "", answerFr: `De procédés de recyclage`, answerCn: `回收利用的方法` },
          { id: 276, topicCn: "", answerFr: `Une paire de lunettes`, answerCn: `一副眼镜` },
          { id: 277, topicCn: "", answerFr: `Ils partent à la montagne`, answerCn: `他们去山里` },
          { id: 278, topicCn: "", answerFr: `Il récupère les cheveux de ses clients pour nettoyer les océans`, answerCn: `他收集顾客的头发来清洁海洋` },
          { id: 279, topicCn: "", answerFr: `Adopter un mode de vie collectif responsable`, answerCn: `采取一种负责任的集体生活方式` },
          { id: 280, topicCn: "", answerFr: `Les partenaires européens trouvent le projet hasardeux`, answerCn: `欧洲合作伙伴认为这个项目风险很大` },

          { type: "section", titleCn: "T29", descFr: "", descCn: "" },
          { id: 281, topicCn: "", answerFr: `D’une campagne d’action sociale`, answerCn: `一场社会行动宣传活动` },
          { id: 282, topicCn: "", answerFr: `Elle va repartir sans sa voiture.`, answerCn: `她将不带车离开。` },
          { id: 283, topicCn: "", answerFr: `Elles assument leurs désirs malgré leur âge`, answerCn: `她们尽管上了年纪，仍坦然接受自己的欲望` },
          { id: 284, topicCn: "", answerFr: `Fonder un foyer.`, answerCn: `建立一个家庭。` },
          { id: 285, topicCn: "", answerFr: `Les accidents peuvent être très graves`, answerCn: `事故可能会非常严重` },
          { id: 286, topicCn: "", answerFr: `La variété de la programmation`, answerCn: `节目安排的多样性` },
          { id: 287, topicCn: "", answerFr: `D’avoir choisi d’y aller seul`, answerCn: `因为选择独自去那里` },
          { id: 288, topicCn: "", answerFr: `Pour éviter les sollicitations abusives.`, answerCn: `为了避免骚扰式招揽。` },
          { id: 289, topicCn: "", answerFr: `Son parcours d’apprentissage`, answerCn: `他的学习历程` },
          { id: 290, topicCn: "", answerFr: `Une naissance.`, answerCn: `一次出生。` },

          { type: "section", titleCn: "T30", descFr: "", descCn: "" },
          { id: 291, topicCn: "", answerFr: `Le recrutement se fonde sur l’expérience.`, answerCn: `招聘以经验为基础。` },
          { id: 292, topicCn: "", answerFr: `Elle trouve le vent trop fort`, answerCn: `她觉得风太大了` },
          { id: 293, topicCn: "", answerFr: `Les écologistes refusent la construction d’une autoroute`, answerCn: `环保人士反对修建一条高速公路` },
          { id: 294, topicCn: "", answerFr: `Les opportunités de carrière.`, answerCn: `职业发展的机会。` },
          { id: 295, topicCn: "", answerFr: `Pour se réchauffer.`, answerCn: `为了取暖。` },
          { id: 296, topicCn: "", answerFr: `Ils osent davantage partir à l’étranger qu’auparavant.`, answerCn: `他们比以前更敢去国外了。` },
          { id: 297, topicCn: "", answerFr: `Ils partent à la montagne`, answerCn: `他们去山里` },
          { id: 298, topicCn: "", answerFr: `Ils voient leur futur de manière positive`, answerCn: `他们以积极的方式看待自己的未来` },
          { id: 299, topicCn: "", answerFr: `Ils devront demander le remboursement de leur billet par écrit.`, answerCn: `他们必须以书面形式申请退还车票费用。` },
          { id: 300, topicCn: "", answerFr: `De maigrir plus rapidement`, answerCn: `为了更快减肥` },

          { type: "section", titleCn: "T31", descFr: "", descCn: "" },
          { id: 301, topicCn: "", answerFr: `Elle va passer la soirée à la maison.`, answerCn: `她要在家里度过这个晚上。` },
          { id: 302, topicCn: "", answerFr: `Les conditions météorologiques.`, answerCn: `天气条件。` },
          { id: 303, topicCn: "", answerFr: `Il cherche à convaincre.`, answerCn: `他试图说服别人。` },
          { id: 304, topicCn: "", answerFr: `Fonder un foyer.`, answerCn: `建立一个家庭。` },
          { id: 305, topicCn: "", answerFr: `Utiliser la littérature comme un support pédagogique`, answerCn: `把文学作为一种教学辅助工具` },
          { id: 306, topicCn: "", answerFr: `Il a travaillé dans un commerce.`, answerCn: `他曾在一家商店工作。` },
          { id: 307, topicCn: "", answerFr: `Parce qu’il manque du personnel aujourd’hui.`, answerCn: `因为如今缺少工作人员。` },
          { id: 308, topicCn: "", answerFr: `Le confort que leur procure leur structure familiale.`, answerCn: `他们的家庭结构给他们带来的安稳感。` },
          { id: 309, topicCn: "", answerFr: `D’éviter des pertes de temps.`, answerCn: `为了避免浪费时间。` },
          { id: 310, topicCn: "", answerFr: `Obtenir un statut professionnel officiel pour les biffins.`, answerCn: `为旧货摊贩获得正式的职业身份。` },

          { type: "section", titleCn: "T32", descFr: "", descCn: "" },
          { id: 311, topicCn: "", answerFr: `Favoriser l’intégration des étrangers.`, answerCn: `促进外国人的融入。` },
          { id: 312, topicCn: "", answerFr: `De préparer des documents pour le comptable..`, answerCn: `准备给会计的文件。` },
          { id: 313, topicCn: "", answerFr: `Le conseil d’un professionnel..`, answerCn: `一位专业人士的建议。` },
          { id: 314, topicCn: "", answerFr: `La mobilité..`, answerCn: `流动性。` },
          { id: 315, topicCn: "", answerFr: `Pour se réchauffer.`, answerCn: `为了取暖。` },
          { id: 316, topicCn: "", answerFr: `Parce que la consommation dépend avant tout du pouvoir d’achat.`, answerCn: `因为消费首先取决于购买力。` },
          { id: 317, topicCn: "", answerFr: `Ses résultats insuffisants.`, answerCn: `他不理想的成绩。` },
          { id: 318, topicCn: "", answerFr: `Parce qu’elles ont beaucoup à apprendre d’eux..`, answerCn: `因为她们有很多东西要向他们学习。` },
          { id: 319, topicCn: "", answerFr: `En les incitant à travailler de manière collaborative.`, answerCn: `通过鼓励他们以合作的方式工作。` },
          { id: 320, topicCn: "", answerFr: `Il donne de l’énergie pour faire face aux épreuves.`, answerCn: `它给予人能量去面对考验。` },

          { type: "section", titleCn: "T33", descFr: "", descCn: "" },
          { id: 321, topicCn: "", answerFr: `Elle voyage souvent.`, answerCn: `她经常旅行。` },
          { id: 322, topicCn: "", answerFr: `Les écologistes refusent la construction d’une autoroute.`, answerCn: `环保人士反对修建一条高速公路。` },
          { id: 323, topicCn: "", answerFr: `Un point de vue sur la situation mondiale aujourd’hui.`, answerCn: `对当今世界局势的一种看法。` },
          { id: 324, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `赋予阅读一种休闲活动的地位。` },
          { id: 325, topicCn: "", answerFr: `Ils ignorent l’origine de leurs plats.`, answerCn: `他们不知道自己菜肴的来源。` },
          { id: 326, topicCn: "", answerFr: `La recherche d’un appartement est rapide.`, answerCn: `找公寓很快。` },
          { id: 327, topicCn: "", answerFr: `Avoir la liberté d’être son propre patron.`, answerCn: `拥有自己当老板的自由。` },
          { id: 328, topicCn: "", answerFr: `Des révisions d’un examen.`, answerCn: `考试复习。` },
          { id: 329, topicCn: "", answerFr: `Faciliter la consommation de produits sains.`, answerCn: `促进健康食品的消费。` },
          { id: 330, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T34", descFr: "", descCn: "" },
          { id: 331, topicCn: "", answerFr: `Le recrutement se fonde sur l’expérience.`, answerCn: `招聘以经验为基础。` },
          { id: 332, topicCn: "", answerFr: `Tourner un film.`, answerCn: `拍摄一部电影。` },
          { id: 333, topicCn: "", answerFr: `Lui présenter son travail.`, answerCn: `向他展示自己的工作。` },
          { id: 334, topicCn: "", answerFr: `Leur salaire est insuffisant.`, answerCn: `他们的工资不足。` },
          { id: 335, topicCn: "", answerFr: `Il veut éviter toute publicité personnelle.`, answerCn: `他想避免任何个人宣传。` },
          { id: 336, topicCn: "", answerFr: `Diffuser des procédés en accord avec la nature.`, answerCn: `传播与自然相协调的方法。` },
          { id: 337, topicCn: "", answerFr: `La recherche d’un appartement est rapide.`, answerCn: `找公寓很快。` },
          { id: 338, topicCn: "", answerFr: `De son emploi du temps professionnel.`, answerCn: `关于他的职业时间安排。` },
          { id: 339, topicCn: "", answerFr: `Elle est restée toute seule.`, answerCn: `她独自一人留下了。` },
          { id: 340, topicCn: "", answerFr: `Aller se promener.`, answerCn: `出去散步。` },

          { type: "section", titleCn: "T35", descFr: "", descCn: "" },
          { id: 341, topicCn: "", answerFr: `Il est possible qu’il soit renvoyé.`, answerCn: `他有可能被解雇。` },
          { id: 342, topicCn: "", answerFr: `Les travaux nécessaires ne sont pas encore achevés.`, answerCn: `所需的工程还没有完成。` },
          { id: 343, topicCn: "", answerFr: `Elle refuse de garder le chien.`, answerCn: `她拒绝照看这只狗。` },
          { id: 344, topicCn: "", answerFr: `Que l’homme se soit mis à faire du sport.`, answerCn: `那个男人开始做运动了。` },
          { id: 345, topicCn: "", answerFr: `Les équipements.`, answerCn: `设备。` },
          { id: 346, topicCn: "", answerFr: `Pour façonner la personnalité de l’enfant.`, answerCn: `为了塑造孩子的个性。` },
          { id: 347, topicCn: "", answerFr: `Il pense qu’il aurait dû être prévenu.`, answerCn: `他认为本来应该有人提前通知他。` },
          { id: 348, topicCn: "", answerFr: `Les avis qu’ils partagent au sujet de l’école.`, answerCn: `他们就学校问题所分享的看法。` },
          { id: 349, topicCn: "", answerFr: `Être serviable avec discrétion/ Assister de façon discrète le client`, answerCn: `低调地乐于助人／以低调的方式协助客户` },
          { id: 350, topicCn: "", answerFr: `De maigrir plus rapidement.`, answerCn: `为了更快减肥。` },

          { type: "section", titleCn: "T36", descFr: "", descCn: "" },
          { id: 351, topicCn: "", answerFr: `Elle va attendre un petit peu.`, answerCn: `她会再稍微等一会儿。` },
          { id: 352, topicCn: "", answerFr: `D’un projet de voyage.`, answerCn: `关于一个旅行计划。` },
          { id: 353, topicCn: "", answerFr: `D’attribuer à la lecture le statut de loisir.`, answerCn: `赋予阅读一种休闲活动的地位。` },
          { id: 354, topicCn: "", answerFr: `Pour affirmer notre personnalité.`, answerCn: `为了彰显我们的个性。` },
          { id: 355, topicCn: "", answerFr: `Pour suivre son compagnon.`, answerCn: `为了跟随她的伴侣。` },
          { id: 356, topicCn: "", answerFr: `Parce que la consommation dépend avant tout du pouvoir d’achat.`, answerCn: `因为消费首先取决于购买力。` },
          { id: 357, topicCn: "", answerFr: `D’avoir choisi d’y aller seul.`, answerCn: `因为选择独自去那里。` },
          { id: 358, topicCn: "", answerFr: `En les incitant à travailler de manière collaborative.`, answerCn: `通过鼓励他们以合作的方式工作。` },
          { id: 359, topicCn: "", answerFr: `Il a décidé d’étudier dans deux différents domaines.`, answerCn: `他决定在两个不同领域学习。` },
          { id: 360, topicCn: "", answerFr: `L’implication active de tous les habitants.`, answerCn: `所有居民的积极参与。` },

          { type: "section", titleCn: "T37", descFr: "", descCn: "" },
          { id: 361, topicCn: "", answerFr: `Manger au restaurant`, answerCn: `在餐馆吃饭` },
          { id: 362, topicCn: "", answerFr: `D’un projet de voyage`, answerCn: `关于一个旅行计划` },
          { id: 363, topicCn: "", answerFr: `Il est ironique`, answerCn: `他很讽刺` },
          { id: 364, topicCn: "", answerFr: `À un poste de responsable du village`, answerCn: `担任村里的一个负责人职位` },
          { id: 365, topicCn: "", answerFr: `Les discours discriminants stéréotypés`, answerCn: `带有歧视性的刻板言论` },
          { id: 366, topicCn: "", answerFr: `Le réalisateur a trouvé que ces verbes résumaient les multiples aspects de la vie`, answerCn: `导演认为这些动词概括了生活的多个方面` },
          { id: 367, topicCn: "", answerFr: `Aux conversations intimes avec les clients`, answerCn: `与顾客之间的私密交谈` },
          { id: 368, topicCn: "", answerFr: `Elle empêche d’admirer le ciel`, answerCn: `它妨碍人们欣赏天空` },
          { id: 369, topicCn: "", answerFr: `Parce que le lieu de stage peut être difficile à trouver`, answerCn: `因为实习地点可能很难找到` },
          { id: 370, topicCn: "", answerFr: `Les skieurs contribuent en partie à la pollution des océans`, answerCn: `滑雪者在一定程度上助长了海洋污染` },

          { type: "section", titleCn: "T38", descFr: "", descCn: "" },
          { id: 371, topicCn: "", answerFr: `La nécessité de trouver un travail`, answerCn: `需要找到一份工作` },
          { id: 372, topicCn: "", answerFr: `De renforcer les relations`, answerCn: `加强彼此关系` },
          { id: 373, topicCn: "", answerFr: `La météo était très mauvaise`, answerCn: `天气非常糟糕` },
          { id: 374, topicCn: "", answerFr: `Un dispositif pour retrouver l’objet volé`, answerCn: `一个用来找回被盗物品的装置` },
          { id: 375, topicCn: "", answerFr: `Fonder un foyer`, answerCn: `建立一个家庭` },
          { id: 376, topicCn: "", answerFr: `Ils voyagent plusieurs fois par an de façon brève`, answerCn: `他们每年会多次进行短途旅行` },
          { id: 377, topicCn: "", answerFr: `De surprendre par son attitude`, answerCn: `因他的态度令人惊讶` },
          { id: 378, topicCn: "", answerFr: `Elle prépare une opération commerciale`, answerCn: `她正在筹备一次商业促销活动` },
          { id: 379, topicCn: "", answerFr: `D’élargir sa recherche d’emploi à d’autres domaines`, answerCn: `把求职范围扩大到其他领域` },
          { id: 380, topicCn: "", answerFr: `Il apportera des maladies inconnues jusqu’à présent`, answerCn: `它将带来迄今未知的疾病` },

          { type: "section", titleCn: "T39", descFr: "", descCn: "" },
          { id: 381, topicCn: "", answerFr: `De réviser les méthodes pédagogiques actuelles`, answerCn: `修订当前的教学方法` },
          { id: 382, topicCn: "", answerFr: `Elle voyage souvent`, answerCn: `她经常旅行` },
          { id: 383, topicCn: "", answerFr: `Lui présenter son travail`, answerCn: `向他展示自己的工作` },
          { id: 384, topicCn: "", answerFr: `Ils préparent les repas de la cantine`, answerCn: `他们准备食堂的饭菜` },
          { id: 385, topicCn: "", answerFr: `Parce qu’elle souhaite changer de destination estivale`, answerCn: `因为她想更换夏季度假目的地` },
          { id: 386, topicCn: "", answerFr: `Une information complète pour le consommateur`, answerCn: `为消费者提供完整的信息` },
          { id: 387, topicCn: "", answerFr: `Elle est en perpétuelle transformation`, answerCn: `它处于不断变化之中` },
          { id: 388, topicCn: "", answerFr: `Il récupère les cheveux de ses clients pour nettoyer les océans`, answerCn: `他收集顾客的头发来清洁海洋` },
          { id: 389, topicCn: "", answerFr: `Un acteur de cinéma`, answerCn: `一位电影演员` },
          { id: 390, topicCn: "", answerFr: `Pour s’acheter une maison`, answerCn: `为了给自己买一套房子` },
          
          { type: "section", titleCn: "T40", descFr: "", descCn: "" },
          { id: 391, topicCn: "", answerFr: `Tourner un film`, answerCn: `拍摄一部电影` },
          { id: 392, topicCn: "", answerFr: `D’un projet de voyage`, answerCn: `关于一个旅行计划` },
          { id: 393, topicCn: "", answerFr: `Ils annonçaient de fausses promotions`, answerCn: `他们宣传虚假的促销活动` },
          { id: 394, topicCn: "", answerFr: `Il n’y a plus de place pour la voiture`, answerCn: `已经没有地方停这辆车了` },
          { id: 395, topicCn: "", answerFr: `Elle a suivi des enseignements variés`, answerCn: `她接受了多种多样的课程教育` },
          { id: 396, topicCn: "", answerFr: `Les cursus sur l’environnement se sont multipliés`, answerCn: `环境相关课程数量增加了` },
          { id: 397, topicCn: "", answerFr: `La création de meubles à partir du recyclage`, answerCn: `利用回收材料制作家具` },
          { id: 398, topicCn: "", answerFr: `Les avis qu’ils partagent au sujet de l’école`, answerCn: `他们就学校问题所分享的看法` },
          { id: 399, topicCn: "", answerFr: `Assister de façon discrète le client`, answerCn: `低调地协助客户` },
          { id: 400, topicCn: "", answerFr: `D’un outil qui facilite l’apprentissage, quel que soit la discipline étudiée`, answerCn: `一种无论学习哪门学科都能促进学习的工具` },
          
          { type: "section", titleCn: "新题", descFr: "", descCn: "" },
          { id: 401, topicCn: "", answerFr: `L'impact financier de la pollution sur les citoyens.`, answerCn: `污染对公民造成的经济影响。` },
          { id: 402, topicCn: "", answerFr: `D'avoir mal nourri son animal.`, answerCn: `没有好好喂养自己的动物。` },
        ];

"""

# ---- Config ----
TACHE = 2             # change to 2/3 if you want
KIND = "a"               # "a" for answers; if you insist, change to "q"
OUT_CSV = Path("assets/tcfcaCO/t2.csv")
# ----------------

import re

def extract_answerfr_strings(text: str) -> list[str]:
    # matches: answerFr: `...`   OR   answerFr: "..."
    pat = re.compile(
        r'answerFr\s*:\s*(?:`(?P<bt>[\s\S]*?)`|"(?P<dq>(?:\\.|[^"\\])*)")'
    )

    answers = []
    for m in pat.finditer(text):
        s = m.group("bt") if m.group("bt") is not None else m.group("dq")
        # if it's the "..." form, unescape (optional but nice)
        if m.group("dq") is not None:
            s = bytes(s, "utf-8").decode("unicode_escape")
        s = (s or "").strip()
        if s:
            answers.append(s)
    return answers


def main():
    answers = extract_answerfr_strings(RAW_JS)

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(["tache", "kind", "idx", "text"])  # 4 columns
        for idx, sentence in enumerate(answers, start=1):
            w.writerow([TACHE, KIND, idx, sentence])

    print("Exported:", OUT_CSV)
    print("Count:", len(answers))


if __name__ == "__main__":
    main()
